# Generated by Django 5.2.8 on 2025-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
