# Generated by Django 5.2.8 on 2025-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailverificationcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email'], name='core_emailv_email_b4e949_idx'),
        ),
    ]
