# Generated by Django 5.2.7 on 2025-11-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='account_confirmed',
        ),
    ]
