# Generated by Django 5.2.8 on 2025-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailverificationcode_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
