# Generated by Django 6.0.4 on 2026-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(choices=[('pending_otp', 'Pending OTP'), ('step_2_profile', 'Step 2 Profile'), ('step_3_academic_kyc', 'Step 3 Academic / KYC'), ('step_4_launch', 'Step 4 Launch'), ('completed', 'Completed')], db_index=True, default='pending_otp', max_length=30),
        ),
    ]
