from __future__ import annotations

import os
import re
import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Callable

from django.conf import settings

from apps.core.utils.signed_tokens import SignedTokenService


class HlsMediaPipelineService:
    def __init__(self):
        self.storage_root = Path(settings.HLS_STORAGE_ROOT)
        self.storage_root.mkdir(parents=True, exist_ok=True)
        self.ffmpeg_binary = settings.FFMPEG_BINARY
        self.enable_encryption = settings.HLS_ENABLE_ENCRYPTION
        self.token_service = SignedTokenService(
            secret=getattr(settings, "HLS_SIGNING_SECRET", None) or settings.SECRET_KEY,
            default_ttl_seconds=settings.HLS_URL_TTL_SECONDS,
            namespace="hls-download",
        )

    def relative_path(self, file_path: Path) -> str:
        return str(file_path.relative_to(self.storage_root)).replace("\\", "/")

    def create_download_token(
        self, relative_path: str, ttl_seconds: int | None = None
    ) -> str:
        return self.token_service.issue(
            {"path": relative_path}, ttl_seconds=ttl_seconds
        )

    def verify_download_token(self, token: str, relative_path: str) -> dict[str, str]:
        payload = self.token_service.verify(token)
        if payload.get("path") != relative_path:
            raise ValueError("Token path mismatch")
        return payload

    def transcode(
        self,
        source_path: Path,
        download_url_builder: Callable[[str], str],
        asset_id: str | None = None,
        segment_time: int = 6,
    ) -> dict[str, object]:
        asset_id = asset_id or uuid.uuid4().hex
        output_dir = self.storage_root / asset_id
        output_dir.mkdir(parents=True, exist_ok=True)

        raw_manifest_path = output_dir / "playlist_raw.m3u8"
        manifest_path = output_dir / "playlist.m3u8"
        segment_template = output_dir / "segment_%05d.ts"
        key_file_path = output_dir / "encryption.key"
        key_info_path = output_dir / "encryption.keyinfo"

        if self.enable_encryption:
            key_file_path.write_bytes(os.urandom(16))
            key_url = download_url_builder(self.relative_path(key_file_path))
            key_info_path.write_text(
                f"{key_url}\n{key_file_path}\n",
                encoding="utf-8",
            )

        command = [
            self.ffmpeg_binary,
            "-y",
            "-i",
            str(source_path),
            "-c:v",
            "libx264",
            "-c:a",
            "aac",
            "-preset",
            "veryfast",
            "-crf",
            "28",
            "-f",
            "hls",
            "-hls_time",
            str(segment_time),
            "-hls_playlist_type",
            "vod",
            "-hls_flags",
            "independent_segments",
            "-hls_segment_filename",
            str(segment_template),
        ]

        if self.enable_encryption:
            command.extend(["-hls_key_info_file", str(key_info_path)])

        command.append(str(raw_manifest_path))

        subprocess.run(command, check=True, capture_output=True, text=True)

        if not raw_manifest_path.exists():
            raise RuntimeError("HLS manifest was not generated by ffmpeg")

        raw_manifest = raw_manifest_path.read_text(encoding="utf-8")
        manifest_path.write_text(
            self._rewrite_manifest(raw_manifest, output_dir, download_url_builder),
            encoding="utf-8",
        )

        segment_files = sorted(
            file_path
            for file_path in output_dir.glob("segment_*.ts")
            if file_path.is_file()
        )

        downloadable_files = [manifest_path, *segment_files]
        if key_file_path.exists():
            downloadable_files.append(key_file_path)

        return {
            "asset_id": asset_id,
            "output_dir": output_dir,
            "manifest_path": manifest_path,
            "raw_manifest_path": raw_manifest_path,
            "segment_files": segment_files,
            "downloadable_files": downloadable_files,
            "key_file_path": key_file_path if key_file_path.exists() else None,
        }

    def _rewrite_manifest(
        self,
        manifest: str,
        output_dir: Path,
        download_url_builder: Callable[[str], str],
    ) -> str:
        rewritten_lines: list[str] = []

        for line in manifest.splitlines():
            stripped = line.strip()
            if not stripped:
                rewritten_lines.append(line)
                continue

            if stripped.startswith("#EXT-X-KEY"):
                match = re.search(r'URI="([^"]+)"', stripped)
                if match:
                    key_uri = match.group(1)
                    key_name = Path(key_uri).name
                    key_path = self.relative_path(output_dir / key_name)
                    stripped = re.sub(
                        r'URI="[^"]+"',
                        f'URI="{download_url_builder(key_path)}"',
                        stripped,
                    )
                rewritten_lines.append(stripped)
                continue

            if stripped.startswith("#"):
                rewritten_lines.append(line)
                continue

            segment_name = Path(stripped).name
            segment_path = self.relative_path(output_dir / segment_name)
            rewritten_lines.append(download_url_builder(segment_path))

        return "\n".join(rewritten_lines) + "\n"

    def list_downloadable_relative_paths(self, asset_id: str) -> list[str]:
        asset_dir = self.storage_root / asset_id
        if not asset_dir.exists():
            raise FileNotFoundError(asset_id)

        relative_paths = []
        for file_path in sorted(asset_dir.iterdir()):
            if file_path.is_file():
                relative_paths.append(self.relative_path(file_path))
        return relative_paths

    def cleanup_asset(self, asset_id: str) -> None:
        asset_dir = self.storage_root / asset_id
        if asset_dir.exists():
            shutil.rmtree(asset_dir)
