# Generated by Django 5.2.8 on 2025-11-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='failed_withdraw_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
