# Generated by Django 5.2.7 on 2025-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_wallet_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('system', 'System')], default='personal', max_length=20),
        ),
    ]
