# Generated by Django 5.2.8 on 2025-11-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_wallet_failed_withdraw_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at']},
        ),
    ]
