# Generated by Django 6.0.4 on 2026-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('system', 'System')], max_length=20),
        ),
    ]
