# Generated by Django 5.2.7 on 2025-11-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('system', 'System')], max_length=20),
        ),
    ]
