# Generated by Django 5.2.7 on 2025-11-12 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
