# Generated by Django 5.2.8 on 2025-11-13 07:30

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_children', to='users.parentprofile')),
            ],
            options={
                'db_table': 'parent_children',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.grade')),
                ('parents', models.ManyToManyField(related_name='student_profiles', through='users.ParentChild', to='users.parentprofile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(related_name='parent_profiles', through='users.ParentChild', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_parents', to='users.studentprofile'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsc_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('tsc_number_certificate', models.FileField(blank=True, null=True, upload_to=apps.users.models.certificate_upload_path, validators=[apps.users.models.validate_pdf])),
                ('academic_certificate', models.FileField(blank=True, null=True, upload_to=apps.users.models.certificate_upload_path, validators=[apps.users.models.validate_pdf])),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('google_refresh_token', models.TextField(blank=True, null=True)),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('grade', models.ManyToManyField(blank=True, null=True, related_name='teacher_grades', to='school.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_profiles',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.teacherprofile')),
            ],
            options={
                'db_table': 'availability',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='users.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.teacherprofile')),
            ],
            options={
                'db_table': 'teacher_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['grade'], name='student_pro_grade_i_c124bf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['school'], name='student_pro_school__ed3de5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentchild',
            unique_together={('parent', 'child')},
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date'], name='availabilit_date_685a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['is_blocked'], name='availabilit_is_bloc_4bd462_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherrating',
            index=models.Index(fields=['rating'], name='teacher_rat_rating_cc6503_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherrating',
            index=models.Index(fields=['created_at'], name='teacher_rat_created_901ef8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrating',
            unique_together={('teacher', 'student')},
        ),
    ]
