# Generated by Django 5.2.7 on 2025-11-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bookings',
        ),
    ]
