# Generated by Django 5.2.7 on 2025-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
