# Generated by Django 5.2.8 on 2025-11-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacherprofile_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='id_number',
            new_name='national_identity_number',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='tsc_number_certificate',
            new_name='teacher_license_certificate',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='tsc_number',
            new_name='teacher_license_number',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='id_number',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='national_identity_card',
            field=models.FileField(blank=True, help_text='National Identity card ', null=True, upload_to='identity_cards/'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='national_identity_number',
            field=models.CharField(blank=True, help_text='National Identity Number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='national_identity_card',
            field=models.FileField(blank=True, null=True, upload_to='identity_cards/'),
        ),
    ]
