# Generated by Django 5.2.7 on 2025-11-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('users', '0002_teacherprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='grade',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_grades', to='school.grade'),
        ),
    ]
