# Generated by Django 5.2.7 on 2025-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_studentprofile_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
