# Generated by Django 5.2.7 on 2025-11-10 15:45

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tsc_number_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.certificate_upload_path, validators=[apps.users.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.certificate_upload_path, validators=[apps.users.models.validate_pdf]),
        ),
    ]
