# Generated by Django 5.2.8 on 2025-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_id_number_teacherprofile_national_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='verification_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='ongoing', max_length=20),
        ),
    ]
