# Generated by Django 5.2.7 on 2025-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='timezone',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
