# Generated by Django 5.2.8 on 2025-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacherprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
