# Generated by Django 5.2.8 on 2025-12-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_school_country'),
        ('users', '0005_teacherprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='school.school'),
        ),
    ]
