# Generated by Django 5.2.8 on 2025-12-16 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_meeting_link_livesession_student_meeting_link_and_more'),
        ('users', '0006_teacherprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_a_lead', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_leads', to='school.course')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='users.studentprofile')),
            ],
            options={
                'db_table': 'student_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='student_lea_created_aa70f7_idx')],
                'unique_together': {('course', 'student_profile')},
            },
        ),
    ]
