# Generated by Django 6.0.4 on 2026-04-11 17:04

import django.db.models.deletion
from django.db import migrations, models


def _map_level_code(grade_level):
    if not grade_level:
        return "continuous"

    normalized = str(grade_level).lower().strip()
    if normalized.startswith("grade"):
        return "k12"
    if normalized in {"college", "university"}:
        return "university"
    return "continuous"


def forwards(apps, schema_editor):
    EducationLevel = apps.get_model("school", "EducationLevel")
    Grade = apps.get_model("school", "Grade")
    StudentProfile = apps.get_model("users", "StudentProfile")
    TeacherProfile = apps.get_model("users", "TeacherProfile")

    levels = {
        level.code: level.id
        for level in EducationLevel.objects.filter(code__in=["k12", "university", "continuous"])
    }

    for student in StudentProfile.objects.select_related("grade").all():
        if student.education_level_id:
            continue
        grade_level = student.grade.level if student.grade_id else None
        student.education_level_id = levels[_map_level_code(grade_level)]
        student.save(update_fields=["education_level"])

    teacher_grades = TeacherProfile.grade.through
    for teacher in TeacherProfile.objects.all():
        if teacher.education_level_id:
            continue

        grade_links = teacher_grades.objects.filter(teacherprofile_id=teacher.id)
        grade_level = None
        if grade_links.exists():
            first = grade_links.first()
            grade = Grade.objects.filter(id=first.grade_id).first()
            grade_level = grade.level if grade else None

        teacher.education_level_id = levels[_map_level_code(grade_level)]
        teacher.save(update_fields=["education_level"])


def backwards(apps, schema_editor):
    StudentProfile = apps.get_model("users", "StudentProfile")
    TeacherProfile = apps.get_model("users", "TeacherProfile")
    StudentProfile.objects.update(education_level=None)
    TeacherProfile.objects.update(education_level=None)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_educationlevel_course_education_level_and_more'),
        ('users', '0007_studentlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.educationlevel'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to='school.educationlevel'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
