# Generated by Django 6.0.4 on 2026-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_educationlevel_course_education_level_and_more'),
        ('users', '0008_studentprofile_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='teacher_grades', to='school.grade'),
        ),
    ]
