# Generated by Django 6.0.4 on 2026-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teacherprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack recipient code for transfers (e.g. RCP_xxxxx)', max_length=100, null=True),
        ),
    ]
