# Generated by Django 6.0.4 on 2026-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teacherprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc')], default='KES', max_length=3),
        ),
    ]
