# Generated by Django 6.0.4 on 2026-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_escrow_wallet_and_paystack'),
        ('users', '0011_remove_teacherprofile_currency_and_more'),
    ]

    operations = [
    ]
