# Generated by Django 6.0.4 on 2026-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20260425_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchild',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='mpesa_billing_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='weekly_spend_limit_kes',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='curriculum_type',
            field=models.CharField(blank=True, choices=[('CBC', 'CBC'), ('8_4_4', '8-4-4'), ('IGCSE', 'IGCSE'), ('OTHER', 'Other')], default='CBC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_learning_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='curriculums_taught',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institution_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tsc_number',
            field=models.CharField(blank=True, help_text='Teachers Service Commission (TSC) number', max_length=50, null=True),
        ),
    ]
