# Generated by Django 5.2.7 on 2025-11-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.grade'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school.assessment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='school.question'),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='live_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='school.livesession'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_booking_links', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_links', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='school_subjects', through='school.StudentSubject', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_links', to='school.subject'),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_materials', to='school.subject'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='school.subject'),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='school.subject'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_links', to='school.subject'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_links', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='school_subjects', through='school.TeacherSubject', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='school.subject'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='school.topic'),
        ),
        migrations.AddField(
            model_name='tutoringbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_bookings', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='tutoringbooking',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_bookings', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_booking_links', to='school.tutoringbooking'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('assessment', 'student')},
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['status'], name='session_boo_status_ef10b7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['created_at'], name='session_boo_created_b0b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student'], name='student_sub_student_083e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['subject'], name='student_sub_subject_29581e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='teachersubject',
            index=models.Index(fields=['teacher'], name='teacher_sub_teacher_fc2ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubject',
            index=models.Index(fields=['subject'], name='teacher_sub_subject_8d2f5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('teacher', 'subject')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='subjects_name_ff98e0_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subjects_code_3f80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject'], name='topics_subject_6c3671_idx'),
        ),
        migrations.AddIndex(
            model_name='subtopic',
            index=models.Index(fields=['topic'], name='subtopics_topic_i_2e7bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='tutoringbooking',
            index=models.Index(fields=['status'], name='tutoring_bo_status_92619c_idx'),
        ),
        migrations.AddIndex(
            model_name='tutoringbooking',
            index=models.Index(fields=['start_at'], name='tutoring_bo_start_a_6b8567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbooking',
            unique_together={('student', 'booking')},
        ),
    ]
