# Generated by Django 5.2.7 on 2025-11-04 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('users', '0002_remove_studentprofile_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringbooking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutoringbooking',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={},
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_start',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='scheduled_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='livesession',
            table=None,
        ),
        migrations.DeleteModel(
            name='StudentBooking',
        ),
        migrations.DeleteModel(
            name='TutoringBooking',
        ),
    ]
