# Generated by Django 5.2.8 on 2025-11-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
