# Generated by Django 5.2.7 on 2025-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
    ]
