# Generated by Django 5.2.7 on 2025-11-04 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_tutoringbooking_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
