# Generated by Django 5.2.8 on 2025-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload PDF, video, or other resources.', null=True, upload_to='subtopics/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload PDF, video, or other resources.', null=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
