# Generated by Django 5.2.7 on 2025-11-04 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_livesession_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
