# Generated by Django 5.2.8 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subtopic_content_file_topic_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionmaterial',
            name='file_url',
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='AssessmentAssignment',
        ),
    ]
