# Generated by Django 5.2.7 on 2025-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_livesession_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='whiteboard_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
