# Generated by Django 5.2.7 on 2025-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_livesession_whiteboard_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
