# Generated by Django 5.2.8 on 2025-11-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_revisionmaterial_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='expires_at',
        ),
    ]
