# Generated by Django 5.2.8 on 2025-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_courseenrollment_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
    ]
