# Generated by Django 5.2.8 on 2025-11-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_courseprogress_subtopicprogress_topicprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtopicprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subtopicprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subtopicprogress',
            name='subtopic',
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topicprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='topicprogress',
            name='topic',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='SubtopicProgress',
        ),
        migrations.DeleteModel(
            name='TopicProgress',
        ),
    ]
