# Generated by Django 5.2.8 on 2025-12-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='school.course'),
        ),
    ]
