# Generated by Django 5.2.8 on 2025-12-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_livesession_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='public_id',
        ),
    ]
