# Generated by Django 5.2.8 on 2025-12-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_livesession_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='school.sessionbooking'),
        ),
    ]
