# Generated by Django 5.2.8 on 2025-12-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_livesession_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livesession',
            old_name='meeting_link',
            new_name='student_meeting_link',
        ),
        migrations.AddField(
            model_name='livesession',
            name='teacher_meeting_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
