# Generated by Django 5.2.8 on 2025-12-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_meeting_link_livesession_student_meeting_link_and_more'),
        ('users', '0007_studentlead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='users.teacherprofile'),
        ),
    ]
