# Generated by Django 6.0.4 on 2026-04-11 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _map_level_code(grade_level):
    if not grade_level:
        return "continuous"

    normalized = str(grade_level).lower().strip()
    if normalized.startswith("grade"):
        return "k12"
    if normalized in {"college", "university"}:
        return "university"
    return "continuous"


def forwards(apps, schema_editor):
    EducationLevel = apps.get_model("school", "EducationLevel")
    Course = apps.get_model("school", "Course")
    SessionBooking = apps.get_model("school", "SessionBooking")
    LiveSession = apps.get_model("school", "LiveSession")

    canonical = {
        "k12": ("K-12", "Primary and secondary education tracks."),
        "university": ("University", "Undergraduate and postgraduate tracks."),
        "continuous": ("Continuous Learning", "Professional and lifelong learning tracks."),
    }

    level_ids = {}
    for code, (name, description) in canonical.items():
        level, _ = EducationLevel.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )
        if level.name != name or level.description != description:
            level.name = name
            level.description = description
            level.save(update_fields=["name", "description"])
        level_ids[code] = level.id

    for course in Course.objects.select_related("grade").all():
        if course.education_level_id:
            continue
        grade_level = course.grade.level if course.grade_id else None
        code = _map_level_code(grade_level)
        course.education_level_id = level_ids[code]
        course.save(update_fields=["education_level"])

    for booking in SessionBooking.objects.select_related("course", "course__education_level", "student", "student__grade").all():
        if booking.education_level_id:
            continue

        if booking.course_id and booking.course and booking.course.education_level_id:
            booking.education_level_id = booking.course.education_level_id
        elif booking.student_id and getattr(booking.student, "grade", None):
            code = _map_level_code(booking.student.grade.level)
            booking.education_level_id = level_ids[code]
        else:
            booking.education_level_id = level_ids["continuous"]
        booking.save(update_fields=["education_level"])

    for live in LiveSession.objects.select_related("course", "course__education_level", "session", "session__education_level").all():
        if live.education_level_id:
            continue

        if live.course_id and live.course and live.course.education_level_id:
            live.education_level_id = live.course.education_level_id
        elif live.session_id and live.session and live.session.education_level_id:
            live.education_level_id = live.session.education_level_id
        else:
            live.education_level_id = level_ids["continuous"]
        live.save(update_fields=["education_level"])


def backwards(apps, schema_editor):
    Course = apps.get_model("school", "Course")
    SessionBooking = apps.get_model("school", "SessionBooking")
    LiveSession = apps.get_model("school", "LiveSession")
    EducationLevel = apps.get_model("school", "EducationLevel")

    Course.objects.update(education_level=None)
    SessionBooking.objects.update(education_level=None)
    LiveSession.objects.update(education_level=None)
    EducationLevel.objects.filter(code__in=["k12", "university", "continuous"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('k12', 'K-12'), ('university', 'University'), ('continuous', 'Continuous Learning')], db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'education_levels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='school.educationlevel'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='school.educationlevel'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_bookings', to='school.educationlevel'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
