# Generated by Django 6.0.4 on 2026-04-24 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_educationlevel_course_education_level_and_more'),
        ('users', '0010_escrow_wallet_and_paystack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_sessions', to='school.course')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_peer_sessions', to='users.studentprofile')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_sessions', to='users.studentprofile')),
            ],
            options={
                'db_table': 'peer_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='peer_sessio_status_55df03_idx'), models.Index(fields=['initiator', 'peer', 'course'], name='peer_sessio_initiat_488479_idx')],
            },
        ),
    ]
