# Generated by Django 6.0.4 on 2026-04-24 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_escrow_wallet_and_paystack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('session_booking', 'Session Booking'), ('live_session', 'Live Session'), ('peer_session', 'Peer Session')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=20)),
                ('reference_id', models.UUIDField(db_index=True, help_text='UUID of the source record (SessionBooking, LiveSession, or PeerSession)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.parentprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.teacherprofile')),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'status'], name='calendar_ev_start_d_776c5a_idx'), models.Index(fields=['reference_id'], name='calendar_ev_referen_4cd3f2_idx'), models.Index(fields=['teacher'], name='calendar_ev_teacher_aa72a0_idx'), models.Index(fields=['student'], name='calendar_ev_student_17cb3b_idx'), models.Index(fields=['parent'], name='calendar_ev_parent__08851f_idx')],
            },
        ),
    ]
